name: dart_basic
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.14.3 <3.0.0"

dependencies:
  flutter_lints:
  intl: ^0.17.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
