on: pull_request

name: Pull Request Validation

jobs:
  build:
    name: Init
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: dart pub get
      - name: Analyze Dart
        run: dart analyze --fatal-infos
